version: '3'

services:
  app:
    restart: always
    build: .
    ports:
      - "8000:8000"
    env_file: "./envs/dev-docker.env"
    networks:
      - traefik-internal
#    depends_on:
#      - test

  redis_worker:
    build: .
    command: "python src/redis_worker.py"
    restart: unless-stopped
    network_mode: "host"
    env_file: "envs/dev-docker.env"
    networks:
      - traefik-internal

#  test:
#    build: .
#    env_file: "envs/dev-docker.env"
#    command: ["pytest", "tst"]

  postgres:
    image: postgres:14.3
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 55432:5432
    networks:
      - traefik-internal
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - traefik-internal

volumes:
  postgres-data:

networks:
  traefik-internal:
    external: true
